### ISSUE TITLE
Zabbix 3.0 doesn't like <httptests /> tag from 3.2 template; script leaves it

### ISSUE THREAD

**Issue by JCCyC** [cavaliercoder/zabbix-template-convertor#1]
I tested zabbix-template-converter on the template included in zabbix-module-systemd. The generated file has only the version and timestamp changed, but in order for 3.0 to accept it I had to remove the <httptests /> tag.

**Comment by cavaliercoder** [comment]
Web scenario exports were introduced in 3.2.0 (see: https://support.zabbix.com/browse/ZBXNEXT-178).

I've added the `FixHttpTests` rule to enforce this constraint.

Many thanks for reporting this issue.
